spring:
  mail:
    username: mfix9634@gmail.com
    password: Ixedmanomber10
    port: 587
    host: smtp.gmail.com
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.debug: true

  kafka:
    bootstrap-servers: kafka:9092